on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Deploy App
      uses: DhrumilGohil/my-first-gitub-action@main
      env:
        HOST_NAME: ${{ secrets.HOST_NAME }}
        HOST_USER: ${{ secrets.HOST_USER }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_PORT: ${{ secrets.DB_PORT }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

#     - name: copy file to server
#       run: bash .github/deploy.sh
      
#     - name: ssh to server
#       run: | 
#             ssh root@168.119.62.116 '
#             cd ~/test
#             composer install
#             # Create .env file (assuming you have all necessary environment variables set as secrets in GitHub)
#             echo "APP_ENV=production" >> .env
#             echo "APP_NAME=Laravel" >> .env
#             echo "APP_DEBUG=false" >> .env
#             echo "DB_CONNECTION=mysql" >> .env
#             echo "DB_HOST=127.0.0.1" >> .env
#             echo "DB_PORT=3306" >> .env
#             echo "DB_DATABASE=laravel" >> .env
#             echo "DB_USERNAME=root" >> .env
#             echo "DB_PASSWORD=Rtcamp@1703" >> .env
#             echo "APP_KEY=" >> .env
#             php artisan migrate:fresh — seed
#             chmod -R o+w storage/ bootstrap/ 
#             php artisan key:generate
#             php artisan cache:clear
#             php artisan config:clear
#             php artisan route:clear
#             php artisan view:clear
#             php artisan config:clear
#             composer dump-autoload 
#             php -S 0.0.0.0:8000 -t public/
#             '
